-- Esquema de la app de entrenamientos.
-- La app lo aplica sola al arrancar; también puedes pegarlo en el SQL Editor de Supabase.

CREATE TABLE IF NOT EXISTS spaces (
  id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  token       text NOT NULL UNIQUE,
  name        text NOT NULL DEFAULT 'Mis entrenamientos',
  weekly_goal integer NOT NULL DEFAULT 4,
  created_at  timestamptz NOT NULL DEFAULT now()
);
-- Cada espacio es un usuario con su propio enlace. El administrador crea y gestiona los demás.
ALTER TABLE spaces ADD COLUMN IF NOT EXISTS is_admin boolean NOT NULL DEFAULT false;
ALTER TABLE spaces ADD COLUMN IF NOT EXISTS disabled boolean NOT NULL DEFAULT false;
-- Si no hay administrador, el espacio más antiguo (el del dueño) pasa a serlo.
UPDATE spaces SET is_admin = true
 WHERE id = (SELECT min(id) FROM spaces) AND NOT EXISTS (SELECT 1 FROM spaces WHERE is_admin);

CREATE TABLE IF NOT EXISTS exercises (
  id        integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  space_id  integer NOT NULL REFERENCES spaces(id) ON DELETE CASCADE,
  name      text NOT NULL,
  muscle    text NOT NULL,
  secondary text NOT NULL DEFAULT '',
  archived  boolean NOT NULL DEFAULT false,
  UNIQUE (space_id, name)
);

CREATE TABLE IF NOT EXISTS sessions (
  id           integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  space_id     integer NOT NULL REFERENCES spaces(id) ON DELETE CASCADE,
  date         date NOT NULL,
  title        text NOT NULL DEFAULT '',
  duration_min integer,
  rpe          integer,
  bodyweight   double precision,
  notes        text NOT NULL DEFAULT '',
  created_at   timestamptz NOT NULL DEFAULT now(),
  updated_at   timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS sessions_space_date ON sessions (space_id, date);
-- Sesión que se está registrando en vivo (se guarda sola mientras entrenas).
ALTER TABLE sessions ADD COLUMN IF NOT EXISTS in_progress boolean NOT NULL DEFAULT false;

CREATE TABLE IF NOT EXISTS session_exercises (
  id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id  integer NOT NULL REFERENCES sessions(id) ON DELETE CASCADE,
  exercise_id integer NOT NULL REFERENCES exercises(id),
  position    integer NOT NULL,
  rest_sec    integer,
  notes       text NOT NULL DEFAULT ''
);
CREATE INDEX IF NOT EXISTS se_session ON session_exercises (session_id);
CREATE INDEX IF NOT EXISTS se_exercise ON session_exercises (exercise_id);

CREATE TABLE IF NOT EXISTS sets (
  id                  integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_exercise_id integer NOT NULL REFERENCES session_exercises(id) ON DELETE CASCADE,
  position            integer NOT NULL,
  reps                integer,
  weight              double precision,
  rir                 integer
);
CREATE INDEX IF NOT EXISTS sets_se ON sets (session_exercise_id);

-- Supabase publica el esquema "public" por su API REST. Activar RLS sin políticas
-- bloquea ese acceso: solo el servidor (que usa la conexión directa) puede leer/escribir.
ALTER TABLE spaces            ENABLE ROW LEVEL SECURITY;
ALTER TABLE exercises         ENABLE ROW LEVEL SECURITY;
ALTER TABLE sessions          ENABLE ROW LEVEL SECURITY;
ALTER TABLE session_exercises ENABLE ROW LEVEL SECURITY;
ALTER TABLE sets              ENABLE ROW LEVEL SECURITY;
