'use strict';

// Grupos musculares disponibles (clave -> etiqueta visible).
const MUSCLES = {
  pecho: 'Pecho',
  espalda: 'Espalda',
  hombros: 'Hombros',
  trapecio: 'Trapecio',
  biceps: 'Bíceps',
  triceps: 'Tríceps',
  antebrazos: 'Antebrazos',
  abdomen: 'Abdomen',
  lumbar: 'Lumbar',
  gluteos: 'Glúteos',
  cuadriceps: 'Cuádriceps',
  isquios: 'Isquiotibiales',
  aductores: 'Aductores',
  pantorrillas: 'Pantorrillas',
  cardio: 'Cardio',
  otro: 'Otro',
};

// [nombre, grupo principal, grupos secundarios]
const DEFAULT_EXERCISES = [
  ['Press banca', 'pecho', ['triceps', 'hombros']],
  ['Press banca inclinado', 'pecho', ['hombros', 'triceps']],
  ['Press con mancuernas', 'pecho', ['triceps', 'hombros']],
  ['Aperturas con mancuernas', 'pecho'],
  ['Cruce de poleas', 'pecho'],
  ['Fondos en paralelas', 'pecho', ['triceps']],
  ['Flexiones de brazos', 'pecho', ['triceps', 'hombros']],
  ['Dominadas', 'espalda', ['biceps']],
  ['Jalón al pecho', 'espalda', ['biceps']],
  ['Remo con barra', 'espalda', ['biceps', 'lumbar']],
  ['Remo con mancuerna', 'espalda', ['biceps']],
  ['Remo en polea baja', 'espalda', ['biceps']],
  ['Pullover en polea', 'espalda'],
  ['Peso muerto', 'espalda', ['gluteos', 'isquios', 'lumbar']],
  ['Press militar', 'hombros', ['triceps']],
  ['Press de hombros con mancuernas', 'hombros', ['triceps']],
  ['Elevaciones laterales', 'hombros'],
  ['Pájaros / Face pull', 'hombros', ['trapecio']],
  ['Encogimientos', 'trapecio'],
  ['Curl con barra', 'biceps', ['antebrazos']],
  ['Curl con mancuernas', 'biceps', ['antebrazos']],
  ['Curl martillo', 'biceps', ['antebrazos']],
  ['Extensión de tríceps en polea', 'triceps'],
  ['Press francés', 'triceps'],
  ['Extensión de tríceps sobre la cabeza', 'triceps'],
  ['Sentadilla', 'cuadriceps', ['gluteos', 'aductores']],
  ['Sentadilla frontal', 'cuadriceps', ['gluteos']],
  ['Prensa de piernas', 'cuadriceps', ['gluteos']],
  ['Zancadas', 'cuadriceps', ['gluteos']],
  ['Sentadilla búlgara', 'cuadriceps', ['gluteos']],
  ['Extensión de cuádriceps', 'cuadriceps'],
  ['Peso muerto rumano', 'isquios', ['gluteos', 'lumbar']],
  ['Curl femoral', 'isquios'],
  ['Hip thrust', 'gluteos', ['isquios']],
  ['Abducción de cadera', 'gluteos'],
  ['Aducción de cadera', 'aductores'],
  ['Elevación de talones', 'pantorrillas'],
  ['Plancha', 'abdomen'],
  ['Crunch abdominal', 'abdomen'],
  ['Elevación de piernas', 'abdomen'],
  ['Rueda abdominal', 'abdomen'],
  ['Hiperextensiones', 'lumbar', ['gluteos']],
  ['Correr', 'cardio'],
  ['Bicicleta', 'cardio'],
  ['Remo (máquina)', 'cardio'],
];

module.exports = { MUSCLES, DEFAULT_EXERCISES };
